version: '3'

services:
  #Reporting database
  cpt-reporting-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crypto-profit-tracker-reporting
    ports:
      - 5436:5432
    networks:
      - backend
  #Operational database
  cpt-operational-db:
    image: postgres
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crypto-profit-tracker
    ports:
      - 5435:5432
    networks:
      - backend
  #Debezium CDC
  debezium:
    image: debezium/connect:1.6
    environment:
#      BOOTSTRAP_SERVERS: kafka:9092
      BOOTSTRAP_SERVERS: ec2-34-250-135-9.eu-west-1.compute.amazonaws.com:9092
      GROUP_ID: 2
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
#      KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
#      VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
#      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
#      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
#    depends_on: [kafka]
    links:
      - cpt-operational-db
    ports:
      - 8084:8083
    networks:
      - backend
  #Redis cache
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - backend
networks:
  backend: